# Reference: Deployments. (2023, September 6). Kubernetes. https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-1-deployment
  labels:
    app: app1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/csci-5409-f23/k8-container-1/app:latest
        imagePullPolicy: Always
        name: app1
        ports:
        - containerPort: 6002
        volumeMounts:
        - name: app-volume
          mountPath: /rabia_PV_dir
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: containers-pvc