# Reference: Service. (2023, October 13). Kubernetes. https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: container-1-service

spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 6002
    targetPort: 6002