# Reference: Create a build configuration file. (n.d.). Google Cloud. https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration
steps:
  # building the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-central1-docker.pkg.dev/csci-5409-f23/k8-container-1/app:latest", "."]

  # pushing container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-central1-docker.pkg.dev/csci-5409-f23/k8-container-1/app:latest"]

  # deploying docker image on GKE cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'apply',
    '-f', 'appPVC.yaml',
    '-f', 'appDeployment.yaml',
    '-f', 'appService.yaml'
  ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-gke-cluster'
